hotelmanagementproject/src/java/com/entities/AgeDiscount.java
package com.entities;

import java.math.BigDecimal;
import java.sql.Connection;
import java.sql.PreparedStatement;

import javax.faces.bean.ManagedBean;
import javax.faces.bean.SessionScoped;

import com.DAO.ConnectorManager;
@ManagedBean(name="agediscount")
@SessionScoped
public class AgeDiscount {
	
	  private int id;
	   private int roomtype_id;
	   private int minAge;
	   private int maxAge;
	   private BigDecimal percent;
	   private boolean isActive;
   
   public int getId() {
		return id;
	}
	public void setId(int id) {
		this.id = id;
	}
	public int getRoomtype_id() {
		return roomtype_id;
	}
	public void setRoomtype_id(int roomtype_id) {
		this.roomtype_id = roomtype_id;
	}
	public int getMinAge() {
		return minAge;
	}
	public void setMinAge(int minAge) {
		this.minAge = minAge;
	}
	public int getMaxAge() {
		return maxAge;
	}
	public void setMaxAge(int maxAge) {
		this.maxAge = maxAge;
	}
	public BigDecimal getPercent() {
		return percent;
	}
	public void setPercent(BigDecimal percent) {
		this.percent = percent;
	}
	public boolean isActive() {
		return isActive;
	}
	public void setActive(boolean isActive) {
		this.isActive = isActive;
	}
	 
	public void delete(int id){
		PreparedStatement ps = null;
		Connection con = null;
		if(id !=0)
		{
		     try
		         {
		        con = ConnectorManager.getConnection();
		        String sql = "DELETE FROM agediscount WHERE id="+id;
		        ps= con.prepareStatement(sql); 
		        int i = ps.executeUpdate();
		         if(i >0){ 
		          System.out.println("Row deleted successfully");
		         }
		       }
		        catch(Exception e)
		          {
		           e.printStackTrace();
		          }
		         finally
		               {
		             try{
		          con.close();
		          ps.close();		
		         }catch(Exception e)
		{
		e.printStackTrace();
		  }
		 }
	   }
     } 
     
   
}

hotelmanagementproject/src/java/com/entities/Room.java
package com.entities;

import java.util.Date;

import javax.faces.bean.ManagedBean;
import javax.faces.bean.SessionScoped;

@ManagedBean(name = "room")
@SessionScoped
public class Room {

    private int id;
    private int roomtype_id;
    private boolean isReserved;
    private boolean isCheckedIn;
    private boolean isCheckedOut;
    private Date checkInDate;
    private Date checkOutDate;
    private int evenBedCount;
    private int oddBedCount;
    private int bunkBedCount;
    private int roomNo;
    private int floorNo;
    
    private static int OnePersonCount;
    private static int TwoPersonCount;
    private static int ThreePersonCount;
    private static int FourPersonCount;
    private static int FivePersonCount;
    private static int SixPersonCount;
    

    public int getId() {
        return id;
    }

    public void setId(int id) {
        this.id = id;
    }

    public int getRoomtype_id() {
        return roomtype_id;
    }

    public void setRoomtype_id(int roomtype_id) {
        this.roomtype_id = roomtype_id;
    }

    public boolean isCheckedIn() {
        return isCheckedIn;
    }

    public void setCheckedIn(boolean isCheckedIn) {
        this.isCheckedIn = isCheckedIn;
    }

    public boolean isCheckedOut() {
        return isCheckedOut;
    }

    public void setCheckedOut(boolean isCheckedOut) {
        this.isCheckedOut = isCheckedOut;
    }

    public Date getCheckInDate() {
        return checkInDate;
    }

    public void setCheckInDate(Date checkInDate) {
        this.checkInDate = checkInDate;
    }

    public Date getCheckOutDate() {
        return checkOutDate;
    }

    public void setCheckOutDate(Date checkOutDate) {
        this.checkOutDate = checkOutDate;
    }

    public boolean isReserved() {
        return isReserved;
    }

    public void setReserved(boolean isReserved) {
        this.isReserved = isReserved;
    }

    public int getEvenBedCount() {
        return evenBedCount;
    }

    public void setEvenBedCount(int evenBedCount) {
        this.evenBedCount = evenBedCount;
    }

    public int getOddBedCount() {
        return oddBedCount;
    }

    public void setOddBedCount(int oddBedCount) {
        this.oddBedCount = oddBedCount;
    }

    public int getBunkBedCount() {
        return bunkBedCount;
    }

    public void setBunkBedCount(int bunkBedCount) {
        this.bunkBedCount = bunkBedCount;
    }

    public int getOnePersonCount() {
        return OnePersonCount;
    }

    public void setOnePersonCount(int OnePersonCount) {
        this.OnePersonCount = OnePersonCount;
    }

    public int getTwoPersonCount() {
        return TwoPersonCount;
    }

    public void setTwoPersonCount(int TwoPersonCount) {
        this.TwoPersonCount = TwoPersonCount;
    }

    public int getThreePersonCount() {
        return ThreePersonCount;
    }

    public void setThreePersonCount(int ThreePersonCount) {
        this.ThreePersonCount = ThreePersonCount;
    }

    public int getFourPersonCount() {
        return FourPersonCount;
    }

    public void setFourPersonCount(int FourPersonCount) {
        this.FourPersonCount = FourPersonCount;
    }

    public int getFivePersonCount() {
        return FivePersonCount;
    }

    public void setFivePersonCount(int FivePersonCount) {
        this.FivePersonCount = FivePersonCount;
    }

    public int getSixPersonCount() {
        return SixPersonCount;
    }

    public void setSixPersonCount(int SixPersonCount) {
        this.SixPersonCount = SixPersonCount;
    }

    public int getRoomNo() {
        return roomNo;
    }

    public void setRoomNo(int roomNo) {
        this.roomNo = roomNo;
    }

    public int getFloorNo() {
        return floorNo;
    }

    public void setFloorNo(int floorNo) {
        this.floorNo = floorNo;
    }

}

hotelmanagementproject/src/java/com/Interface/OrderBean.java
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.Interface;

import com.DAO.BillDAO;
import com.DAO.CustomerDAO;
import com.DAO.OrderDAO;
import com.DAO.OrderTypeDAO;
import com.entities.Bill;
import com.entities.Customer;
import com.entities.Human;
import com.entities.Order;
import com.entities.OrderType;
import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import javax.faces.bean.ManagedBean;
import javax.faces.bean.SessionScoped;

/**
 *
 * @author UGUR
 */
@ManagedBean
@SessionScoped
public class OrderBean {

    ArrayList<OrderType> OrderTypes;
    ArrayList<OrderObj> OrderList = new ArrayList<OrderObj>();
    String EmployeeDep = "";
    String CustomerId = "";

    public String getCustomerId() {
        return CustomerId;
    }

    public void setCustomerId(String CustomerId) {
        this.CustomerId = CustomerId;
    }

    public ArrayList<OrderObj> getList() {
        return OrderList;
    }

    // get set
    String count;

    public String getCount() {
        return count;
    }

    public void setCount(String count) {
        this.count = count;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }
    String name = "";

    public OrderBean() {
        // OrderTypes= OrderTypeDAO.select();
    }

    public void addtoOrderList() {
        try {
            OrderObj temp = new OrderObj();
            String tempname = name;
            int TempOrderid = 0;
            if (name.contains(":")) {
                String[] parts = tempname.split(":");
                tempname = parts[parts.length - 1];
                TempOrderid = Integer.valueOf(tempname);
            }
            if (TempOrderid != 0) {
                temp.Type = OrderTypeDAO.selectOne(TempOrderid);
                temp.Count = Integer.valueOf(count);
                OrderList.add(temp);
            }
            // sıfırlıyoruz
            count = "";
            name = "";
        } catch (Exception e) {
        }
        System.out.println("Siparis Sayisi " + name + " " + count);
    }

    public void removeFromOrderList(int x) {
        try {
            OrderList.remove(x);
        } catch (Exception e) {
        }

    }

    public void savetoOrderList() {

        Customer temp = CustomerDAO.selectOne(CustomerId);

        if (temp != null) {
            int tempbillid = -1;
            String tempcustomerid = temp.getID();
            try {

                Customer templeader = temp.getLeader();
                if (templeader != null) {
                    tempcustomerid = templeader.getID();
                }

                tempbillid = BillDAO.selectLastBillID(tempcustomerid);
            } catch (Exception e) {

            }

            if (tempbillid == 0) { // odenmemis fatura yoksa yanlis kisiye cikiyodur
                System.out.println("Odenmemis fatura yok son fatura bulunamadi geri donuldu");
                return;
            }
            for (int i = 0; i < OrderList.size(); i++) {
                Order yeni = new Order();
                yeni.setType(OrderList.get(i).Type);
                yeni.setCount(OrderList.get(i).Count);
                yeni.CustomerID = tempcustomerid;
                yeni.BillID = tempbillid;
                yeni.DateTime = new Date(); // simdiki zamani yaziyoruz 
                OrderDAO.insert(yeni); // eklediii :) 
            }
            cleanOrderList(); // listeyi temizliyoruz
        } else {
            System.out.println("Bu id de musteri yok");
        }

    }

    public void cleanOrderList() {
        OrderList = new ArrayList<OrderObj>();
    }

    public String getAllOrderTypes(String Department) {
        if (EmployeeDep.equals("")) {
            EmployeeDep = Department;
            try {
                int dep = Integer.valueOf(EmployeeDep);
                OrderTypes = OrderTypeDAO.selectByDepartment(dep);
            } catch (Exception e) {
                OrderTypes = OrderTypeDAO.select();
            }
        }
        String Temp = "[";
        for (int i = 0; i < OrderTypes.size(); i++) {
            Temp = Temp + "\"" + OrderTypes.get(i).Description + "    No:" + OrderTypes.get(i).getID() + "\",";
        }
        Temp = Temp + "\"Yok\"]";
        return Temp;
    }

    public class OrderObj {

        OrderType Type;
        int Count = 0;
        String CountStr = "";

        public String getCountStr() {
            CountStr = String.valueOf(Count);
            return CountStr;
        }

        public void setCountStr(String CountStr) {
            this.CountStr = CountStr;
        }
        String name = "";
        String price = "";
        String totalprice = "";

        public String getTotalprice() {
            BigDecimal total = Type.Prize.multiply(new BigDecimal(Count)); // carpma islemi
            totalprice = String.valueOf(total);
            return totalprice;
        }

        public void setTotalprice(String totalprice) {
            this.totalprice = totalprice;
        }

        public String getPrice() {
            this.price = String.valueOf(Type.Prize);
            return price;
        }

        public void setPrice(String price) {
            this.price = price;
        }

        public String getName() {
            this.name = Type.Description;
            return name;
        }

        public void setName(String name) {

            this.name = name;
        }

    }
}

hotelmanagementproject/web/methodKullanimi/delete.xhtml
<?xml version="1.0" encoding="ISO-8859-1" ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xmlns:f="http://java.sun.com/jsf/core" xmlns:h="http://java.sun.com/jsf/html">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=ISO-8859-1" />
<title>Insert title here</title>
</head>
<body>
<f:view>
      <h1>JSF Delete Data From The Database Table Example</h1>
<h:form id="form1">
<h:dataTable value="#{roomtypedao.select()}" var="u" border="1">
<h:column>
<f:facet name="header">
 ID
</f:facet>
#{u.id}
</h:column>

<h:column>
<f:facet name="header">
EvenBed
</f:facet>
#{u.evenBed}
</h:column>

<h:column>
<f:facet name="header">
OddBed
</f:facet>
#{u.oddBed}
</h:column>

<h:column>
<f:facet name="header">
BunkBed
</f:facet>
#{u.bunkBed}
</h:column>

<h:column>
<f:facet name="header">
BedCount
</f:facet>
#{u.bedCount}
</h:column>

<h:column>
<f:facet name="header">
PrizePerDay
</f:facet>
#{u.prizePerDay}
</h:column>

<h:column>
<h:commandButton value="DELETE" action="#{roomtype.delete(u.id)}" />

</h:column>
</h:dataTable>
</h:form>


<h:form id="form2">
<h:dataTable value="#{agediscountdao.select()}" var="u" border="1">
<h:column>
<f:facet name="header">
 ID
</f:facet>
#{u.id}
</h:column>

<h:column>
<f:facet name="header">
Room_Type
</f:facet>
#{u.roomtype_id}
</h:column>

<h:column>
<f:facet name="header">
MinAge
</f:facet>
#{u.minAge}
</h:column>

<h:column>
<f:facet name="header">
MaxAge
</f:facet>
#{u.maxAge}
</h:column>

<h:column>
<f:facet name="header">
Percent
</f:facet>
#{u.percent}
</h:column>

<h:column>
<f:facet name="header">
Active
</f:facet>
#{u.active}
</h:column>

<h:column>
<h:commandButton value="DELETE" action="#{agediscount.delete(u.id)}" />

</h:column>
</h:dataTable>
</h:form>
</f:view>
</body>
</html>

hotelmanagementproject/web/methodKullanimi/insert.xhtml
<?xml version="1.0" encoding="ISO-8859-1" ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xmlns:f="http://java.sun.com/jsf/core" xmlns:h="http://java.sun.com/jsf/html">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=ISO-8859-1" />
<title>Insert title here</title>
</head>
<body>
<f:view>
     <h:form> 
    <fieldset>
   <legend><p class="col"> Personel Settings for Sign Up to Site</p></legend>
<table style="background-color: #ECE5B6;" WIDTH="30%">
<tr>
<td> <h:messages showDetail="true" /> </td>
</tr>

<tr>
<td width="50%"><h:outputText value="Enter Id : "/></td>
<td width="50%"><h:inputText value="#{roomtypedao.id}"/></td>
</tr>

<tr>
<td width="50%"><h:outputText value="EvenBedCount : " /></td>
<td width="50%"><h:inputText value="#{roomtypedao.evenBed}" /></td>
</tr>

<tr>
<td width="50%"><h:outputText value="OddBedCount : "/></td>
<td width="50%"><h:inputText value="#{roomtypedao.oddBed}" /></td>
</tr>

<tr>
<td width="50%"><h:outputText value="BunkBedCount:"/></td>
<td width="50%"><h:inputText value="#{roomtypedao.bunkBed}" /></td>
</tr>

<tr>
<td width="50%"><h:outputText value="BedCount:"/></td>
<td width="50%"><h:inputText value="#{roomtypedao.bedCount}" /></td>
</tr>

<tr>
<td width="50%"><h:outputText value="Prize Per Day:"/></td>
<td width="50%"><h:inputText value="#{roomtypedao.prizePerDay}" /></td>
</tr>



<tr>
<td width="50%"><h:commandButton value="Add" action="#{roomtypedao.insert()}"/></td>
</tr>

</table>
<br/><br/>

<table style="background-color: #ECE5B6;" WIDTH="30%">
<tr>
<td> <h:messages showDetail="true" /> </td>
</tr>

<tr>
<td width="50%"><h:outputText value="Enter Id : "/></td>
<td width="50%"><h:inputText value="#{agediscountdao.id}"/></td>
</tr>

<tr>
<td width="50%"><h:outputText value="RoomType_Id : " /></td>
<td width="50%"><h:inputText value="#{agediscountdao.roomtype_id}" /></td>
</tr>

<tr>
<td width="50%"><h:outputText value="MinAge : "/></td>
<td width="50%"><h:inputText value="#{agediscountdao.minAge}" /></td>
</tr>

<tr>
<td width="50%"><h:outputText value="MaxAge:"/></td>
<td width="50%"><h:inputText value="#{agediscountdao.maxAge}" /></td>
</tr>

<tr>
<td width="50%"><h:outputText value="Percent"/></td>
<td width="50%"><h:inputText value="#{agediscountdao.percent}" /></td>
</tr>

<tr>
<td width="50%"><h:outputText value="isActive"/></td>
<td width="50%"><h:inputText value="#{agediscountdao.active}" /></td>
</tr>


<tr>
<td width="50%"><h:commandButton value="Add" action="#{agediscountdao.insert()}"/></td>
</tr>

</table>
<br/><br/>
<table style="background-color: #ECE5B6;" WIDTH="30%">
<tr>
<td> <h:messages showDetail="true" /> </td>
</tr>

<tr>
<td width="50%"><h:outputText value="Enter Id : "/></td>
<td width="50%"><h:inputText value="#{packagediscountdao.id}"/></td>
</tr>

<tr>
<td width="50%"><h:outputText value="RoomType_Id : " /></td>
<td width="50%"><h:inputText value="#{packagediscountdao.roomtype_id}" /></td>
</tr>

<tr>
<td width="50%"><h:outputText value="DayCount: "/></td>
<td width="50%"><h:inputText value="#{packagediscountdao.daycount}" /></td>
</tr>

<tr>
<td width="50%"><h:outputText value="NightCount:"/></td>
<td width="50%"><h:inputText value="#{packagediscountdao.nightcount}" /></td>
</tr>

<tr>
<td width="50%"><h:outputText value="Percent"/></td>
<td width="50%"><h:inputText value="#{packagediscountdao.percent}" /></td>
</tr>

<tr>
<td width="50%"><h:outputText value="isActive"/></td>
<td width="50%"><h:inputText value="#{packagediscountdao.active}" /></td>
</tr>


<tr>
<td width="50%"><h:commandButton value="Add" action="#{packagediscountdao.insert()}"/></td>
</tr>

</table>
<br/><br/>
<table style="background-color: #ECE5B6;" WIDTH="30%">
<tr>
<td> <h:messages showDetail="true" /> </td>
</tr>

<tr>
<td width="50%"><h:outputText value="Enter Id : "/></td>
<td width="50%"><h:inputText value="#{reservationdao.id}"/></td>
</tr>

<tr>
<td width="50%"><h:outputText value="Enter RoomId : " /></td>
<td width="50%"><h:inputText value="#{reservationdao.roomId}" /></td>
</tr>

<tr>
<td width="50%"><h:outputText value="Enter CustomerId: "/></td>
<td width="50%"><h:inputText value="#{reservationdao.customerId}" /></td>
</tr>

<tr>
<td width="50%"><h:outputText value="Enter BillId:"/></td>
<td width="50%"><h:inputText value="#{reservationdao.billId}" /></td>
</tr>



<tr>
<td width="50%"><h:commandButton value="Add" action="#{reservationdao.insert()}"/></td>
</tr>

</table>
 </fieldset>
</h:form>


<h:form>
<table>
<tr>
<td> <h:messages showDetail="true" /> </td>
</tr>
<tr>
<td><h:outputText value="Enter Id : "/></td>
<td><h:inputText value="#{roomdao.id}"/></td>
</tr>
<tr>
<td><h:outputText value="Enter Room Type Id : " /></td>
<td><h:inputText value="#{roomdao.roomtype_id}" /></td>
</tr>
<tr>
<td><h:outputText value="Enter isReserved : "/></td>
<td><h:inputText value="#{roomdao.reserved}" /></td>
</tr>
<tr>
<td><h:outputText value="Enter isCheckIn : "/></td>
<td><h:inputText value="#{roomdao.checkedIn}" /></td>
</tr>
<tr>
<td><h:outputText value="Enter isCheckOut : "/></td>
<td><h:inputText value="#{roomdao.checkedOut}" /></td>
</tr>
<tr>
<td><h:outputText value="Enter CheckInDate: "/></td>
<td><h:inputText value="#{roomdao.checkInDate}">
<f:convertDateTime pattern="yyyy-MM-dd"/>
</h:inputText></td>
</tr>
<tr>
<td><h:outputText value="Enter CheckOutDate: "/></td>
<td><h:inputText value="#{roomdao.checkOutDate}">
<f:convertDateTime pattern="yyyy-MM-dd"/>
</h:inputText></td>
</tr>
<tr>
<td></td>
<td><h:commandButton value="Insert" action="#{roomdao.insert()}"/></td>
</tr>
</table>
</h:form>
</f:view>
</body>
</html>

hotelmanagementproject/web/methodKullanimi/invalid.xhtml
<?xml version="1.0" encoding="ISO-8859-1" ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xmlns:f="http://java.sun.com/jsf/core" xmlns:h="http://java.sun.com/jsf/html">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=ISO-8859-1" />
<title>Insert title here</title>
</head>
<body>
<f:view>
     <p>Invalidation </p>
</f:view>
</body>
</html>

hotelmanagementproject/web/methodKullanimi/update.xhtml
<?xml version="1.0" encoding="ISO-8859-1" ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xmlns:f="http://java.sun.com/jsf/core" xmlns:h="http://java.sun.com/jsf/html">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=ISO-8859-1" />
<title>Insert title here</title>
</head>
<body>
<f:view>
  <h:form>
    <h:commandButton value="Update" action="#{roomtypedao.update(200)}"></h:commandButton>
    <h:commandButton value="Update2" action="#{agediscountdao.update(200)}"></h:commandButton>
    <h:commandButton value="Update3" action="#{packagediscountdao.update(200)}"></h:commandButton>
    
    <br/><br/>
    <h:commandButton value="UpdateRoom" action="#{reservationdao.updateRoom(3)}"></h:commandButton><br/>
    <h:commandButton value="UpdateCustomer" action="#{reservationdao.updateCustomer(2)}"></h:commandButton><br/>
    <h:commandButton value="UpdateBill" action="#{reservationdao.updateBill(3)}"></h:commandButton><br/>
   </h:form>
</f:view>
</body>
</html>