hotelmanagementproject/src/java/com/Interface/ImageSearchBean.java
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package com.Interface;

import java.io.BufferedReader;
import java.io.InputStreamReader;
import java.net.HttpURLConnection;
import java.net.URL;
import java.util.ArrayList;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.faces.bean.ManagedBean;
import javax.faces.bean.RequestScoped;

/**
 *
 * @author UGUR
 */
@ManagedBean
@RequestScoped
public class ImageSearchBean {
    public String text="";
    public String url="http://yandex.com.tr/gorsel/search?text=";
    public final String USER_AGENT = "Mozilla/5.0";
         ArrayList<String> titles = new ArrayList<String>();

    public ArrayList<String> getTitles() {
        return titles;
    }

    public void setTitles(ArrayList<String> titles) {
        this.titles = titles;
    }
    /**
     * Creates a new instance of ImageSearchBean
     */
    public ImageSearchBean() {
    }

    public String getText() {
        return text;
    }

    public void setText(String text) {
        this.text = text;
    }
    
    
    public void GoWeb(){
        if(text.contains(" ")){
            text=text.replace(" ", "%20");
        }
       titles = new ArrayList<String>();
        StringBuffer response = new StringBuffer();
        try{
            
 
		URL obj = new URL(url+text);
		HttpURLConnection con = (HttpURLConnection) obj.openConnection();
 
		// optional default is GET
		con.setRequestMethod("GET");
 
		//add request header
		con.setRequestProperty("User-Agent", USER_AGENT);
 
		int responseCode = con.getResponseCode();
	
 
		BufferedReader in = new BufferedReader(
		        new InputStreamReader(con.getInputStream()));
		String inputLine;
		response = new StringBuffer();
 
		while ((inputLine = in.readLine()) != null) {
			response.append(inputLine);
		}
		in.close();
 
		//print result
                      //  titles.add(response.toString()); 
   Matcher matcher = Pattern.compile("&quot;href&quot;:&quot;(.*?)&quot;").matcher(response.toString());
while(matcher.find()){
    titles.add(matcher.group(1));
}
        System.out.println();
        }catch(Exception e){}
      
      if(titles==null){
          titles= new ArrayList<String>();
      }

       
        
    }
    
    
    
    
}

hotelmanagementproject/src/java/com/Interface/OrderBean.java
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.Interface;

import com.DAO.BillDAO;
import com.DAO.CustomerDAO;
import com.DAO.OrderDAO;
import com.DAO.OrderTypeDAO;
import com.entities.Bill;
import com.entities.Customer;
import com.entities.Human;
import com.entities.Order;
import com.entities.OrderType;
import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import javax.faces.bean.ManagedBean;
import javax.faces.bean.SessionScoped;

/**
 *
 * @author UGUR
 */
@ManagedBean
@SessionScoped
public class OrderBean {

    ArrayList<OrderType> OrderTypes;
    ArrayList<OrderObj> OrderList = new ArrayList<OrderObj>();
    String EmployeeDep = "";
    String CustomerId = "";

    public String getCustomerId() {
        return CustomerId;
    }

    public void setCustomerId(String CustomerId) {
        this.CustomerId = CustomerId;
    }

    public ArrayList<OrderObj> getList() {
        return OrderList;
    }

    // get set
    String count;

    public String getCount() {
        return count;
    }

    public void setCount(String count) {
        this.count = count;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }
    String name = "";

    public OrderBean() {
        // OrderTypes= OrderTypeDAO.select();
    }

    public void addtoOrderList() {
        try {
            OrderObj temp = new OrderObj();
            String tempname = name;
            int TempOrderid = 0;
            if (name.contains(":")) {
                String[] parts = tempname.split(":");
                tempname = parts[parts.length - 1];
                TempOrderid = Integer.valueOf(tempname);
            }
            if (TempOrderid != 0) {
                temp.Type = OrderTypeDAO.selectOne(TempOrderid);
                temp.Count = Integer.valueOf(count);
                OrderList.add(temp);
            }
            // sıfırlıyoruz
            count = "";
            name = "";
        } catch (Exception e) {
        }
        System.out.println("Siparis Sayisi " + name + " " + count);
    }

    public void removeFromOrderList(int x) {
        try {
            OrderList.remove(x);
        } catch (Exception e) {
        }

    }

    public void savetoOrderList() {

        Customer temp = CustomerDAO.selectOne(CustomerId);

        if (temp != null) {
            int tempbillid = -1;
            String tempcustomerid = temp.getID();
            try {

                Customer templeader = temp.getLeader();
                if (templeader != null) {
                    tempcustomerid = templeader.getID();
                }

                tempbillid = BillDAO.selectLastBillID(tempcustomerid);
            } catch (Exception e) {

            }

            if (tempbillid == 0) { // odenmemis fatura yoksa yanlis kisiye cikiyodur
                System.out.println("Odenmemis fatura yok son fatura bulunamadi geri donuldu");
                return;
            }
            for (int i = 0; i < OrderList.size(); i++) {
                Order yeni = new Order();
                yeni.setType(OrderList.get(i).Type);
                yeni.setCount(OrderList.get(i).Count);
                yeni.CustomerID = tempcustomerid;
                yeni.BillID = tempbillid;
                yeni.DateTime = new Date(); // simdiki zamani yaziyoruz 
                OrderDAO.insert(yeni); // eklediii :) 
            }
            cleanOrderList(); // listeyi temizliyoruz
        } else {
            System.out.println("Bu id de musteri yok");
        }

    }

    public void cleanOrderList() {
        OrderList = new ArrayList<OrderObj>();
    }

    public String getAllOrderTypes(String Department) {
        if (EmployeeDep.equals("")) {
            EmployeeDep = Department;
            try {
                int dep = Integer.valueOf(EmployeeDep);
                OrderTypes = OrderTypeDAO.selectByDepartment(dep);
            } catch (Exception e) {
                OrderTypes = OrderTypeDAO.select();
            }
        }
        String Temp = "[";
        for (int i = 0; i < OrderTypes.size(); i++) {
            Temp = Temp + "\"" + OrderTypes.get(i).Description + "    No:" + OrderTypes.get(i).getID() + "\",";
        }
        Temp = Temp + "\"Yok\"]";
        return Temp;
    }

    public class OrderObj {

        OrderType Type;
        int Count = 0;
        String CountStr = "";

        public String getCountStr() {
            CountStr = String.valueOf(Count);
            return CountStr;
        }

        public void setCountStr(String CountStr) {
            this.CountStr = CountStr;
        }
        String name = "";
        String price = "";
        String totalprice = "";

        public String getTotalprice() {
            BigDecimal total = Type.Prize.multiply(new BigDecimal(Count)); // carpma islemi
            totalprice = String.valueOf(total);
            return totalprice;
        }

        public void setTotalprice(String totalprice) {
            this.totalprice = totalprice;
        }

        public String getPrice() {
            this.price = String.valueOf(Type.Prize);
            return price;
        }

        public void setPrice(String price) {
            this.price = price;
        }

        public String getName() {
            this.name = Type.Description;
            return name;
        }

        public void setName(String name) {

            this.name = name;
        }

    }
}

hotelmanagementproject/web/addon/editCustomerInfo.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://xmlns.jcp.org/jsf/html">
    <h:head>
        <title></title>
        <link href="/hotelmanagementproject/assets/plugins/font-awesome/css/font-awesome.min.css" rel="stylesheet" type="text/css" />
   <link href="/hotelmanagementproject/assets/plugins/bootstrap/css/bootstrap.min.css" rel="stylesheet" type="text/css" />
   <link href="/hotelmanagementproject/assets/plugins/uniform/css/uniform.default.css" rel="stylesheet" type="text/css" />
      <link rel="stylesheet" type="text/css" href="/hotelmanagementproject/assets/plugins/select2/select2_metro.css" />
      <link rel="stylesheet" href="/hotelmanagementproject/assets/plugins/data-tables/DT_bootstrap.css" />
        <link href="/hotelmanagementproject/assets/css/style-metronic.css" rel="stylesheet" type="text/css" />
   <link rel="stylesheet" type="text/css" href="/hotelmanagementproject/assets/plugins/bootstrap-datepicker/css/datepicker.css" />
   <link href="/hotelmanagementproject/assets/css/style.css" rel="stylesheet" type="text/css" />
   <link href="/hotelmanagementproject/assets/css/style-responsive.css" rel="stylesheet" type="text/css" />
   <link href="/hotelmanagementproject/assets/css/plugins.css" rel="stylesheet" type="text/css" />
   <link href="/hotelmanagementproject/assets/css/themes/default.css" rel="stylesheet" type="text/css" id="style_color" />
   <link href="/hotelmanagementproject/assets/css/custom.css" rel="stylesheet" type="text/css" />
    </h:head>
    <h:body>
        
        <h:form id="form1"  style="color: white;">
            <h:inputText  class="form-control" id="txtdeneme" value="#{customerara.cusID}"></h:inputText><h:commandButton class=" form-control btn blue" value="Ara" action="faces/addon/editCustomerInfo.xhtml" actionListener="#{customerara.getInfo(e)}"></h:commandButton>           
            <div><span class="form-control">Name : </span><h:inputText class="form-control" value="#{customerara.cusName}"></h:inputText></div>
            <div><span class="form-control">Surname : </span><h:inputText class="form-control" value="#{customerara.cusSurname}"></h:inputText></div>
            <div><span class="form-control">Mail : </span><h:inputText class="form-control" value="#{customerara.cusMail}"></h:inputText></div>
            <div><span class="form-control">Phone : </span><h:inputText class="form-control" value="#{customerara.cusPhone}"></h:inputText></div>
            <div><span class="form-control">Birth : </span><h:inputText class="form-control" value="#{customerara.cusBirth}"></h:inputText></div>
            <div><h:commandButton value="Degisiklikleri Kaydet" class="form-control" action="faces/addon/editCustomerInfo.xhtml" actionListener="#{customerara.saveInfo(e)}"></h:commandButton></div>
            <h:inputText style='display: none;' id="result" value="#{customerara.saveResult}"></h:inputText>
        </h:form>
        <script type="text/javascript">
            
            var data = window.location.search;
            
            if(data.indexOf('?') != -1){
            
            var dataClean;
            
            dataClean = data.split('=');
            
            document.getElementById('form1:txtdeneme').value = dataClean[1];           
            }
            function kapat(){
                
                if(document.getElementById("form1:result").value == "1"){
                    window.close();
                }
                
            }
            kapat();
        </script>
    </h:body>
</html>


hotelmanagementproject/web/addon/getcustomer.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets">
    <h:head>
        <title>Facelet Title</title>
           <link href="/hotelmanagementproject/assets/plugins/font-awesome/css/font-awesome.min.css" rel="stylesheet" type="text/css" />
   <link href="/hotelmanagementproject/assets/plugins/bootstrap/css/bootstrap.min.css" rel="stylesheet" type="text/css" />
   <link href="/hotelmanagementproject/assets/plugins/uniform/css/uniform.default.css" rel="stylesheet" type="text/css" />
      <link rel="stylesheet" type="text/css" href="/hotelmanagementproject/assets/plugins/select2/select2_metro.css" />
      <link rel="stylesheet" href="/hotelmanagementproject/assets/plugins/data-tables/DT_bootstrap.css" />
        <link href="/hotelmanagementproject/assets/css/style-metronic.css" rel="stylesheet" type="text/css" />
   <link rel="stylesheet" type="text/css" href="/hotelmanagementproject/assets/plugins/bootstrap-datepicker/css/datepicker.css" />
   <link href="/hotelmanagementproject/assets/css/style.css" rel="stylesheet" type="text/css" />
   <link href="/hotelmanagementproject/assets/css/style-responsive.css" rel="stylesheet" type="text/css" />
   <link href="/hotelmanagementproject/assets/css/plugins.css" rel="stylesheet" type="text/css" />
   <link href="/hotelmanagementproject/assets/css/themes/default.css" rel="stylesheet" type="text/css" id="style_color" />
   <link href="/hotelmanagementproject/assets/css/custom.css" rel="stylesheet" type="text/css" />
    </h:head>
    <h:body>
        <div class="page-content">
            <h:form>
        <div class="form-group">
                             
                                            <label class="control-label col-md-3">Müşteri Arama</label>
                                  <div class="input-group" style="text-align:left">
                                      <h:inputText id="musteriid" class="form-control" value="#{customerara.aranacak}" /> 
                                    <span class="input-group-btn">
                                       
                                    
                                        <h:commandLink onclick="#{customerara.Search()}" class="btn yellow">Müşteri Ara <i class="icon-search"></i></h:commandLink>
                                     
                                       
                                    </span>
                                 
                                 </div>
                                           
                                 
                              
                           </div>
                         
            <table class="table table-hover table-striped table-bordered">
                        <tbody>
                             <ui:repeat varStatus="status" var="item" value="#{customerara.list}" > 
                                
                            <tr>
                                <td>#{customerara.getUser(status.index)}</td>
                           <td><a class="btn default" data-toggle="modal" href="#" onclick="gerigonder('#{customerara.getUserID(status.index)}')">Seç</a></td>
                        </tr>
                             </ui:repeat>
                     </tbody></table>
                                 
                              
                           
            </h:form>
       
    

<script>
    function gerigonder(a){
      //  window.opener['output'].value = document.getElementById('user_text').value;
      window.opener['output'].value = a;
        window.close();
    }
</script>
        </div>
    </h:body>
</html>


hotelmanagementproject/web/addon/imagesearch.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets">
    <h:head>
        <title>Facelet Title</title>
           <link href="/hotelmanagementproject/assets/plugins/font-awesome/css/font-awesome.min.css" rel="stylesheet" type="text/css" />
   <link href="/hotelmanagementproject/assets/plugins/bootstrap/css/bootstrap.min.css" rel="stylesheet" type="text/css" />
   <link href="/hotelmanagementproject/assets/plugins/uniform/css/uniform.default.css" rel="stylesheet" type="text/css" />
      <link rel="stylesheet" type="text/css" href="/hotelmanagementproject/assets/plugins/select2/select2_metro.css" />
      <link rel="stylesheet" href="/hotelmanagementproject/assets/plugins/data-tables/DT_bootstrap.css" />
        <link href="/hotelmanagementproject/assets/css/style-metronic.css" rel="stylesheet" type="text/css" />
   <link rel="stylesheet" type="text/css" href="/hotelmanagementproject/assets/plugins/bootstrap-datepicker/css/datepicker.css" />
   <link href="/hotelmanagementproject/assets/css/style.css" rel="stylesheet" type="text/css" />
   <link href="/hotelmanagementproject/assets/css/style-responsive.css" rel="stylesheet" type="text/css" />
   <link href="/hotelmanagementproject/assets/css/plugins.css" rel="stylesheet" type="text/css" />
   <link href="/hotelmanagementproject/assets/css/themes/default.css" rel="stylesheet" type="text/css" id="style_color" />
   <link href="/hotelmanagementproject/assets/css/custom.css" rel="stylesheet" type="text/css" />
    </h:head>
    <h:body>
        <div class="page-content">
            <h:form>
        <div class="form-group">
                             
                                            <label class="control-label col-md-3">Resim Arama</label>
                                  <div class="input-group" style="text-align:left">
                                      <h:inputText id="musteriid" class="form-control" value="#{imageSearchBean.text}" /> 
                                    <span class="input-group-btn">
                                       
                                    
                                        <h:commandLink onclick="#{imageSearchBean.GoWeb()}" class="btn yellow">Resim Ara <i class="icon-search"></i></h:commandLink>
                                     
                                       
                                    </span>
                                 
                                 </div>
                                           
                                 
                              
                           </div>
                         
            <table class="table table-hover table-striped table-bordered">
                        <tbody>
                            <ui:repeat varStatus="status" var="item" value="#{imageSearchBean.titles}" > 
                                
                            <tr>
                                <td><img src="#{item}" height="100" /></td>
                           <td><a class="btn default" data-toggle="modal" href="#" onclick="gerigonder('#{item}')">Seç</a></td>
                        </tr>
                             </ui:repeat>
                     </tbody></table>
                                 
                              
                           
            </h:form>
       
    

<script>
    function gerigonder(a){
      //  window.opener['output'].value = document.getElementById('user_text').value;
      window.opener['output'].value = a;
        window.close();
    }
</script>
        </div>
    </h:body>
</html>
