hotelmanagementproject/src/java/com/entities/Department.java
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package com.entities;

import java.util.ArrayList;

/**
 *
 * @author Erel
 */
public class Department {
    private int ID;
    public String Name;
    public String Description;
    public int EmployeeCount;
    public ArrayList<Employee> Employees;
    
    public Department(){
        
    }
    
    public Department(int id){
        if(id > 0){
            this.ID = id;
        }
    }
    
    public int getID(){
        return this.ID;
    }

    public String getName() {
        return Name;
    }

    public void setName(String Name) {
        this.Name = Name;
    }

    public String getDescription() {
        return Description;
    }

    public void setDescription(String Description) {
        this.Description = Description;
    }

    public int getEmployeeCount() {
        return EmployeeCount;
    }

    public void setEmployeeCount(int EmployeeCount) {
        this.EmployeeCount = EmployeeCount;
    }
    
    public boolean addEmployee( Employee value ){
        if(this.Employees == null){
            this.Employees = new ArrayList<Employee>();
        }
        if(this.Employees.contains(value)){
            return false;
        }else{
            boolean rvalue = this.Employees.add(value);
            this.EmployeeCount = Employees.size();
            return rvalue;
        }
    }
    
    public boolean removeEmployee( Employee value ){
        if(this.Employees == null){
            return false;
        }else{
            if(this.Employees.contains(value)){
                boolean rvalue = this.Employees.remove(value);
                this.EmployeeCount = Employees.size();
                return rvalue;
            }else{
                return false;
            }
        }
    }
}

hotelmanagementproject/src/java/com/entities/Expense.java
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package com.entities;

import java.math.BigDecimal;
import java.util.Date;

/**
 *
 * @author Erel
 */
public class Expense extends PaymentRecord{
    public int DepartmentID;
    public String Description;
    public BigDecimal Prize;
    
    public Expense(){
        
    }
    public Expense(int id){
        super(id);
    }

    public int getDepartmentID() {
        return DepartmentID;
    }

    public void setDepartmentID(int DepartmentID) {
        this.DepartmentID = DepartmentID;
    }

    public String getDescription() {
        return Description;
    }

    public void setDescription(String Description) {
        this.Description = Description;
    }

    public BigDecimal getPrize() {
        return Prize;
    }

    public void setPrize(BigDecimal Prize) {
        this.Prize = Prize;
    }

    public Date getDateTime() {
        return DateTime;
    }

    public void setDateTime(Date DateTime) {
        this.DateTime = DateTime;
    }
    
}

hotelmanagementproject/src/java/com/Interface/ExpenseBean.java
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package com.Interface;

import com.DAO.DepartmentDAO;
import com.DAO.ExpenseDAO;
import com.DAO.ReservationDao;
import com.entities.Department;
import com.entities.Expense;
import java.math.BigDecimal;
import java.util.ArrayList;
import javax.faces.bean.ManagedBean;
import javax.faces.bean.SessionScoped;

/**
 *
 * @author Erel
 */
@ManagedBean
@SessionScoped
public class ExpenseBean {

    String ID;
    String DepartmentId;
    String Department;
    String Description;
    String Price;
    String DateTime;
    
    Expense temp;
    
    ArrayList<Expense> expList = new ArrayList<Expense>();
    
    public ExpenseBean() {
    }

    public String getID() {
        return ID;
    }

    public void setID(String ID) {
        this.ID = ID;
    }
    
    public String getDepartmentId() {
        return DepartmentId;
    }

    public void setDepartmentId(String DepartmentId) {
        this.DepartmentId = DepartmentId;
    }

    public String getDepartment() {
        return Department;
    }

    public void setDepartment(String Department) {
        this.Department = Department;
    }

    public String getDescription() {
        return Description;
    }

    public void setDescription(String Description) {
        this.Description = Description;
    }

    public String getPrice() {
        return Price;
    }

    public void setPrice(String Price) {
        this.Price = Price;
    }

    public String getDateTime() {
        return DateTime;
    }

    public void setDateTime(String DateTime) {
        this.DateTime = DateTime;
    }

    public ArrayList<Expense> getExpList() {
        return expList;
    }

    public void setExpList(ArrayList<Expense> expList) {
        this.expList = expList;
    }
    
    public void edit(String id) {
        temp = ExpenseDAO.selectOne(Integer.parseInt(id));
        show();
    }
    
    public void delete(int id) {
         Expense temp2= new Expense(id);
         ExpenseDAO.delete(temp2);
         AllExpenses();
    }

    public void show() {
        if (temp == null) {
            return;
        }
        
        ID = String.valueOf(temp.getID());
        DepartmentId = String.valueOf(temp.DepartmentID);
        Department = DepartmentDAO.getName(temp.DepartmentID);
        Description = temp.Description;
        Price = String.valueOf(temp.Prize);
        DateTime = String.valueOf(temp.DateTime);

    }

    public void save() {
        int tempId;
        try{
            tempId = Integer.parseInt(ID);
        }catch(NumberFormatException nfe){
            tempId = 0;
        }
        temp = new Expense(tempId);
        temp.DepartmentID = Integer.parseInt(DepartmentId);
        temp.Description = Description;
        temp.Prize = new BigDecimal(Price);
        temp.DateTime = new ReservationDao().formatMe(DateTime);
        
        Expense temp2 = ExpenseDAO.selectOne(tempId);
        if(temp2 == null){
            ExpenseDAO.insert(temp);
        }else{
            ExpenseDAO.update(temp);
        }
        AllExpenses();
        ID = "0";
    }
    
    public String allDepartments() {
        ArrayList<Department> list = DepartmentDAO.select();
        String Temp = "[";
        for (int i = 0; i < list.size(); i++) {
            Temp = Temp + "\"" + list.get(i).Description + "    No:" + list.get(i).getID() + "\",";
        }
        Temp = Temp + "\"Yok\"]";
        return Temp;
    }

    public void AllExpenses() {
        expList = ExpenseDAO.select();
    }
    
    public String departmentName(int DepartmentID){
        return DepartmentDAO.getName(DepartmentID);
    }
}

hotelmanagementproject/src/java/com/Interface/LoginBean.java
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package com.Interface;

import com.DAO.EmployeeDAO;
import com.entities.Employee;
import javax.faces.bean.ManagedBean;
import javax.faces.bean.SessionScoped;

/**
 *
 * @author UGUR
 */
@ManagedBean(name = "LoginBean")
@SessionScoped
public class LoginBean {
    public String tempID=""; // temp id on login
    public String Pass="";   // temp pass on logined
    public String ID="";     // id after login
    public String Username="Deneme Soyadı"; // Username After login
    public Boolean Logined=false; // is login check
    public int Logintryed=0; // is login check
    public String Pagename="main.xhtml";   // the main page after logined
    public int DepartmentID = 1;
    Employee Person= new Employee();
   // Temp Person Profile For Edit
    private String T_name="";
    private String T_surname;
    private String T_phone;
    private String T_Salary;
    private String T_about;
    private String T_password;
    private String T_password2;

    
    public void getProfile(){
        T_name = Person.Name;
T_surname = Person.Surname;
T_phone =   Person.Phone;
T_Salary =   Person.Salary.toString();
T_about = Person.JobDescription;
T_password = Person.getPassword();
    }
    
    public String getDepartmentEmployee(){
        System.out.println("Departman id si alındı LoginBean dan sonuc :"+Person.DepartmentID);
        return String.valueOf(Person.DepartmentID);
    }
    
    public String saveProfile(){
Person.Phone=T_phone;
if(T_password.equals(T_password2))
Person.setPassword(T_password);
EmployeeDAO.update(Person); // update user profile
        return "index.xhtml";
    }
    
    public String getPagename() {
        return Pagename;
        
    }

    public void setPagename(String Pagename) {
        this.Pagename = Pagename;
    }
    
    public String getTempID() {
        return tempID;
    }

    public void setTempID(String tempID) {
        this.tempID = tempID;
    }

    public String getPass() {
        return Pass;
    }

    public void setPass(String Pass) {
        this.Pass = Pass;
    }
    
        public String setPage(String num){
        this.Pagename=num;
        return "index.xhtml";
    }

    public String getUsername() {
        return Username;
    }

    public void setUsername(String Username) {
        this.Username = Username;
    }
    
    public LoginBean() {
        
    }
    
     public String isLogin(){
         if(!Logined)
        Login();
        if(Logined)
            return "index2.xhtml";
       return "login.xhtml";
    }
    
    public void Login(){
     if(      Logined= Employee.login(tempID,Pass)){
          ID=tempID;
         Person= new Employee(tempID,Pass);
       Person= EmployeeDAO.selectOne(ID);
       if(Person!=null){
           DepartmentID = Person.DepartmentID;
           Username=Person.Name+" "+Person.Surname;  
       }       
         Logintryed=0;
     }
     else{
         Logintryed++; // tryed to login
     }
        
          
    }
    
    
    public void Logout(){
        Logintryed=0;
        Logined=false;
        tempID=""; // temp id on login
        Pass="";   // temp pass on logined
        ID="";     // id after login
    }
    
    public String ShowError(){
        if(Logintryed>1)
        return "<div id=\"forget\" class=\"alert-box error\"><span>Hata: </span>Hatalı Giriş</bold></bold></div>";
        return "";
    }
    
    
    public String unique(int sira){
        if((sira==1 || sira==2 || sira==3 ||sira==4 ||sira==5)&& (DepartmentID==4 || DepartmentID==5 || DepartmentID==6))
            return "hidden";
        if(sira==6 || sira==7)
           return "";
        if((sira==8)&& (DepartmentID==1 || DepartmentID==4 || DepartmentID==5 || DepartmentID==6 ))
            return "hidden";
        if((sira==9 || sira==10 ||sira==11 )&& (DepartmentID==1 || DepartmentID==2 || DepartmentID==4 || DepartmentID==5 || DepartmentID==6 ))
            return "hidden";
        return "";
        
    }
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    public String getT_password2() {
        return T_password2;
    }

    public void setT_password2(String T_password2) {
        this.T_password2 = T_password2;
    }

    public String getT_name() {
        return T_name;
    }

    public void setT_name(String T_name) {
        this.T_name = T_name;
    }

    public String getT_surname() {
        return T_surname;
    }

    public void setT_surname(String T_surname) {
        this.T_surname = T_surname;
    }

    public String getT_phone() {
        return T_phone;
    }

    public void setT_phone(String T_phone) {
        this.T_phone = T_phone;
    }

    public String getT_Salary() {
        return T_Salary;
    }

    public void setT_Salary(String T_Salary) {
        this.T_Salary = T_Salary;
    }

    public String getT_about() {
        return T_about;
    }

    public void setT_about(String T_about) {
        this.T_about = T_about;
    }

    public String getT_password() {
        return T_password;
    }

    public void setT_password(String T_password) {
        this.T_password = T_password;
    }
    
}

hotelmanagementproject/src/java/com/Interface/RoomBean.java
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package com.Interface;

import com.DAO.RoomDao;
import com.DAO.RoomTypeDao;
import com.entities.RoomType;
import com.entities.Room;
import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Date;
import javax.faces.bean.ManagedBean;
import javax.faces.bean.SessionScoped;

/**
 *
 * @author Erel
 */
@ManagedBean
@SessionScoped
public class RoomBean {
    
    String ID;
    String RoomNo;
    String FloorNo;
    String RoomTypeID;
    String RoomType;
    boolean isReserved;
    boolean isCheckedIn;
    boolean isCheckedOut;
    Date checkInDate;
    Date checkOutDate;
    
    ArrayList<Room> roomList = new ArrayList<Room>();
    
    public ArrayList<Room> getRoomList() {
        return roomList;
    }
    
    public void setRoomList(ArrayList<Room> roomList) {
        this.roomList = roomList;
    }
    
    Room temp;
    
    public RoomBean() {
    }
    
    public String getRoomNo() {
        return RoomNo;
    }
    
    public void setRoomNo(String RoomNo) {
        this.RoomNo = RoomNo;
    }
    
    public String getFloorNo() {
        return FloorNo;
    }
    
    public void setFloorNo(String FloorNo) {
        this.FloorNo = FloorNo;
    }
    
    public String getRoomTypeID() {
        return RoomTypeID;
    }
    
    public void setRoomTypeID(String RoomTypeID) {
        this.RoomTypeID = RoomTypeID;
    }
    
    public String getRoomType() {
        return RoomType;
    }
    
    public void setRoomType(String RoomType) {
        this.RoomType = RoomType;
    }
    
    public Room getTemp() {
        return temp;
    }
    
    public void setTemp(Room temp) {
        this.temp = temp;
    }
    
    public String allRoomTypes() {
        ArrayList<RoomType> list = new RoomTypeDao().select();
        String Temp = "[";
        for (int i = 0; i < list.size(); i++) {
            Temp = Temp + "\"" + list.get(i).getDescription() + "    No:" + list.get(i).getId() + "\",";
        }
        Temp = Temp + "\"Yok\"]";
        return Temp;
    }
    
    public void edit(int id) {
        temp = new RoomDao().selectOne(id).get(0);
        show();
    }
    
    public void delete(int id) {
        new RoomDao().delete(id);
    }
    
    public void show() {
        if (temp == null) {
            return;
        }
        ID = String.valueOf(temp.getId());
        RoomNo = String.valueOf(temp.getRoomNo());
        FloorNo = String.valueOf(temp.getFloorNo());
        RoomTypeID = String.valueOf(temp.getRoomtype_id());
        RoomType = String.valueOf(RoomTypeDao.getName(temp.getRoomtype_id()));
        isReserved = temp.isReserved();
        isCheckedOut = temp.isCheckedOut();
        isCheckedIn = temp.isCheckedIn();
        checkInDate = temp.getCheckInDate();
        checkOutDate = temp.getCheckOutDate();
    }
    
    public void save() {        
        RoomDao manipulator = new RoomDao();
        try{
         manipulator.setId(Integer.parseInt(ID));   
        }catch(Exception e){
        manipulator.setId(0);
          }
        manipulator.setRoomNo(Integer.parseInt(RoomNo));
        manipulator.setFloorNo(Integer.parseInt(FloorNo));
        manipulator.setRoomtype_id(Integer.parseInt(RoomTypeID));
        manipulator.setReserved(isReserved);
        manipulator.setCheckedIn(isCheckedIn);
        manipulator.setCheckedOut(isCheckedOut);
        manipulator.setCheckInDate(checkInDate);
        manipulator.setCheckOutDate(checkInDate);
        Room temp2=null;
        try{
          temp2    = new RoomDao().selectOne(Integer.parseInt(ID)).get(0);
        }
        catch(Exception e){

            System.out.println("Exe girdi");
        }
       
        if (temp2 == null) {
            manipulator.insertNewRoom(RoomNo, FloorNo, RoomTypeID);
        } else {
            manipulator.update();
        }
        ID="0";
        AllRooms();
    }
    
    public void AllRooms() {
        roomList = new RoomDao().select();
    }
    
    public String RoomTypeName(int RoomTypeID) {
        return RoomTypeDao.getName(RoomTypeID);
    }
    
}

hotelmanagementproject/web/expense_table.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<!--
To change this license header, choose License Headers in Project Properties.
To change this template file, choose Tools | Templates
and open the template in the editor.
-->
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:f="http://xmlns.jcp.org/jsf/core"
      >
    
    <script>
        function degisti(){
            var degisken = document.getElementById('buradan').value;
            degisken = degisken.split(":");
            document.getElementById('sip:veri').value=degisken[1];
        }
    </script>

    <h:body>
        <h3 class="form-section">Gider İşlemleri</h3>



        <div class="form-group">

            <h:form id="sip">

                <div class="col-md-3">

                    <div class="form-group">
                        <label class="control-label">Tarih </label>
                        <h:inputText   class="form-control" value="#{expenseBean.dateTime}" /> 
                    </div>
                    <div class="form-group">
                        <label class="control-label">Açıklama </label>
                        <h:inputText   class="form-control" value="#{expenseBean.description}" /> 
                    </div>
                    <div class="form-group">
                        <label class="control-label">Tutar </label>
                        <h:inputText   class="form-control" value="#{expenseBean.price}" /> 
                    </div>
                    <div class="form-group">
                        <label class="control-label">Departman</label>
                      
                            <input  id="buradan" class="form-control" autocomplete="off" data-provide="typeahead" data-items="4" data-source='#{expenseBean.allDepartments()}'/>

                            <h:inputText id="veri" value="#{expenseBean.departmentId}" style="visibility: hidden"/>

                    </div>
                    

                    <div class="form-group" style="position:relative;">
                        <span class="input-group-btn">


                            <h:commandLink class="btn green" id="username1_checker" action="#{expenseBean.save()}" onclick="degisti()" > <i class="icon-ok"></i> Kaydet </h:commandLink>

                        </span>
                    </div>
                </div>

            </h:form>
            <div class="col-md-8" style="float: right;">

                <div class="portlet box blue">
                    <div class="portlet-title">
                        <div class="caption"><i class="icon-user"></i>Giderler</div>
                    </div>
                    <div class="portlet-body">
                        <div class="table-responsive">
                            <table class="table table-hover">
                                <thead>
                                    <tr>
                                        <th>#</th>
                                        <th>Tarih</th>
                                        <th>Departman</th>
                                        <th>Açıklama</th>
                                        <th>Tutar</th>

                                    </tr>
                                </thead>
                                <tbody>
                                    <ui:repeat varStatus="status" var="item" value="#{expenseBean.expList}" > 
                                        <tr>
                                            <td>#{status.index} </td>
                                            <td>#{item.dateTime} </td>
                                            <td>#{expenseBean.departmentName(item.departmentID)}</td>
                                            <td>#{item.description}</td>
                                            <td>#{item.prize}</td>

                                            <td><h:form>
                                                    <h:commandLink action="#{expenseBean.edit(item.ID)}" class="btn btn-xs blue"> Düzenle <i class="icon-edit"></i> </h:commandLink>

                                                    <h:commandLink action="#{expenseBean.delete(item.ID)}" class="btn btn-xs red"> Sil <i class="icon-remove"></i> </h:commandLink> 
                                                </h:form>    </td>
                                        </tr>

                                    </ui:repeat>

                                </tbody>
                            </table>
                            <div class="col-md-12">
                                <div class="col-md-offset-3" style="float: right;position:relative;top:20px;">
                                    <h:form>  <h:commandButton action="#{expenseBean.AllExpenses()}" class="btn blue button-next"  value="Giderleri Göster"/> </h:form>

                                </div>
                            </div>

                        </div>
                    </div>
                </div>



            </div>

        </div>



    </h:body>
</html>

hotelmanagementproject/web/profile.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:f="http://xmlns.jcp.org/jsf/core">
    <h:head>
        <title>EDUE</title>
    </h:head>
    <h:body>
        <h:form>
            <h3 class="form-section">Kullanıcı Bilgileri</h3>
          #{LoginBean.getProfile()}
            
            
                                       <div class="form-group">
                                          <label class="control-label">Adı</label>
                                          <h:inputText value="#{LoginBean.t_name}" class="form-control" disabled="true" />                                          
                                       </div>
                                       <div class="form-group">
                                          <label class="control-label">Soyadı</label>
                                          <h:inputText value="#{LoginBean.t_surname}" class="form-control" disabled="true" />
                                       </div>
                                       <div class="form-group">
                                          <label class="control-label">Telefon No</label>
                                          <h:inputText value="#{LoginBean.t_phone}" class="form-control" />
                                       </div>
                                       <div class="form-group">
                                          <label class="control-label">Yeni Şifre</label>
                                          <h:inputText value="#{LoginBean.t_password}" class="form-control" />
                                       </div>
                                        <div class="form-group">
                                          <label class="control-label">Yeni Şifre Tekrar</label>
                                          <h:inputText value="#{LoginBean.t_password2}" class="form-control" />
                                       </div>
                                       <div class="form-group">
                                          <label class="control-label">Maaş Bilgileri</label>
                                          <h:inputText value="#{LoginBean.t_Salary}" class="form-control" disabled="true" />
                                       </div>
                                       <div class="form-group">
                                          <label class="control-label">İş Açıklaması</label>
                                          
                                          <h:inputTextarea value="#{LoginBean.t_about}" rows="3" class="form-control" disabled="true"  />
                                         
                                       </div>
            
                                       <div class="margiv-top-10">
                                           <h:commandLink action="#{LoginBean.saveProfile()}" class="btn green"> Kaydet</h:commandLink> 
                                           <h:commandLink action="index.xhtml" class="btn default"> Vazgeç</h:commandLink>
                                       </div>
                                    </h:form>
    </h:body>
</html>


hotelmanagementproject/web/sub0.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<!--
To change this license header, choose License Headers in Project Properties.
To change this template file, choose Tools | Templates
and open the template in the editor.
-->
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml">
   
   
</html>

hotelmanagementproject/web/type_table.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<!--
To change this license header, choose License Headers in Project Properties.
To change this template file, choose Tools | Templates
and open the template in the editor.
-->
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:f="http://xmlns.jcp.org/jsf/core"
      >
    
    <script>
        function degisti(){
            var degisken = document.getElementById('buradan').value;
            degisken = degisken.split(":");
            document.getElementById('sip:veri').value=degisken[1];
        }
    </script>

    <h:body>
        <h3 class="form-section">Ürün İşlemleri</h3>



        <div class="form-group">

            <h:form id="sip">

                <div class="col-md-3">

                    <div class="form-group">
                        <label class="control-label">Ücretsiz Pansiyon </label>
                        <h:inputText   class="form-control" value="#{orderTypeBean.minPension}" /> 
                    </div>
                    <div class="form-group">
                        <label class="control-label">Açıklama </label>
                        <h:inputText   class="form-control" value="#{orderTypeBean.description}" /> 
                    </div>
                    <div class="form-group">
                        <label class="control-label">Tutar </label>
                        <h:inputText   class="form-control" value="#{orderTypeBean.price}" /> 
                    </div>
                    <div class="form-group">
                        <label class="control-label">Departman</label>
                      
                        <input  id="buradan" class="form-control" autocomplete="off" data-provide="typeahead" data-items="4" data-source='#{orderTypeBean.allDepartments()}'/>

                            <h:inputText id="veri" value="#{orderTypeBean.departmentId}" style="visibility: hidden"/>

                    </div>
                    

                    <div class="form-group" style="position:relative;">
                        <span class="input-group-btn">


                            <h:commandLink class="btn green" id="username1_checker" action="#{orderTypeBean.save()}" onclick="degisti()" > <i class="icon-ok"></i> Kaydet </h:commandLink>

                        </span>
                    </div>
                </div>

            </h:form>
            <div class="col-md-8" style="float: right;">

                <div class="portlet box blue">
                    <div class="portlet-title">
                        <div class="caption"><i class="icon-user"></i>Ürünler</div>
                    </div>
                    <div class="portlet-body">
                        <div class="table-responsive">
                            <table class="table table-hover">
                                <thead>
                                    <tr>
                                        <th>#</th>
                                        <th>Ücretsiz pansiyon</th>
                                        <th>Departman</th>
                                        <th>Açıklama</th>
                                        <th>Tutar</th>

                                    </tr>
                                </thead>
                                <tbody>
                                    <ui:repeat varStatus="status" var="item" value="#{orderTypeBean.typeList}" > 
                                        <tr>
                                            <td>#{status.index} </td>
                                            <td>#{item.minPrizelessPension} </td>
                                            <td>#{expenseBean.departmentName(item.departmentID)}</td>
                                            <td>#{item.description}</td>
                                            <td>#{item.prize}</td>

                                            <td><h:form>
                                                    <h:commandLink action="#{orderTypeBean.edit(item.ID)}" class="btn btn-xs blue"> Düzenle <i class="icon-edit"></i> </h:commandLink>

                                                    <h:commandLink action="#{orderTypeBean.delete(item.ID)}" class="btn btn-xs red"> Sil <i class="icon-remove"></i> </h:commandLink> 
                                                </h:form>    </td>
                                        </tr>

                                    </ui:repeat>

                                </tbody>
                            </table>
                            <div class="col-md-12">
                                <div class="col-md-offset-3" style="float: right;position:relative;top:20px;">
                                    <h:form>  <h:commandButton action="#{orderTypeBean.AllTypes()}" class="btn blue button-next"  value="Ürünleri Göster"/> </h:form>

                                </div>
                            </div>

                        </div>
                    </div>
                </div>



            </div>

        </div>



    </h:body>
</html>